# Generated by Django 3.1.5 on 2021-01-17 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210116_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(max_length=100, unique=True)),
                ('dob', models.DateField(default=0.0005025125628140704)),
                ('profile_pic', models.ImageField(blank=True, default='PP.jpg', null=True, upload_to='profile_pics')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('city', models.CharField(choices=[('Wah', 'Wah'), ('Taxila', 'Taxila'), ('Kohat', 'Kohat'), ('Vehari', 'Vehari'), ('Chakwal', 'Chakwal'), ('Kalar Kahar', 'Kalar Kahar'), ('Sangla Hill', 'Sangla Hill'), ('Shah Kot', 'Shah Kot'), ('Gojra', 'Gojra'), ('Toba Tek Singh', 'Toba Tek Singh'), ('Multan', 'Multan')], max_length=500, null=True)),
                ('area', models.CharField(max_length=500, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
