# Generated by Django 3.1.5 on 2021-01-17 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210117_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(max_length=100, unique=True)),
                ('dob', models.DateField(default=1988)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True)),
                ('city', models.CharField(choices=[('Wah', 'Wah'), ('Taxila', 'Taxila'), ('Kohat', 'Kohat'), ('Vehari', 'Vehari'), ('Chakwal', 'Chakwal'), ('Kalar Kahar', 'Kalar Kahar'), ('Sangla Hill', 'Sangla Hill'), ('Shah Kot', 'Shah Kot'), ('Gojra', 'Gojra'), ('Toba Tek Singh', 'Toba Tek Singh'), ('Multan', 'Multan')], max_length=500, null=True)),
                ('area', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(default='PP.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
