# Generated by Django 3.1.5 on 2021-01-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210118_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cnic',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
