# Generated by Django 3.1.5 on 2021-01-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210118_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutMe',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='postalCode',
            field=models.IntegerField(null=True),
        ),
    ]
