# Generated by Django 3.1.5 on 2021-01-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210126_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
