# Generated by Django 3.1.5 on 2021-03-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210306_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('Director', 'Director'), ('Manager', 'Manager'), ('Team Lead', 'Team_Lead'), ('Member', 'Member')], null=True),
        ),
    ]
