# Generated by Django 3.1.5 on 2021-03-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210319_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Director'), (2, 'Manager'), (3, 'Team_Lead'), (4, 'Member')], null=True),
        ),
    ]
